fix(handle uv_os_get_passwd error)
See https://github.com/stepankuzmin/tilelive-postgis/issues/10 

When running an application in Openshift Origin (kubernetes, docker) each call to `$node.health` causes something like
```
[2018-10-20T20:28:38.445Z] ERROR service-33-2g5bm-7/HEALTH:    Request error! Error : ENOENT: no such file or directory, uv_os_get_passwd 
 Error: ENOENT: no such file or directory, uv_os_get_passwd
    at getOsInfo (/app/node_modules/moleculer/src/health.js:53:12)
```

Fix is pretty the same as for `tilelive-postgis`